# Generated by Django 5.0.1 on 2024-09-15 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='token_id',
        ),
        migrations.AddField(
            model_name='nft',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nft',
            name='ipfs_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('buyer_wallet', models.CharField(max_length=255)),
                ('seller_wallet', models.CharField(max_length=255)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.nft')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
