# Generated by Django 5.0.1 on 2024-09-19 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_nft_created_at_remove_nft_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='for_sale',
            new_name='is_listed',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='ipfs_link',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller_wallet',
        ),
        migrations.AddField(
            model_name='nft',
            name='contract_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='token_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='token_uri',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_nfts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
