# Generated by Django 5.0.1 on 2024-09-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='nft',
        ),
        migrations.AddField(
            model_name='auction',
            name='creator_name',
            field=models.CharField(help_text='Name of the original creator/artist', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(help_text='Detailed description of the NFT', null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='nft_collection',
            field=models.CharField(blank=True, help_text='Collection the NFT belongs to', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='nft_image',
            field=models.URLField(blank=True, help_text='URL of the NFT image or media', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='nft_title',
            field=models.CharField(help_text='Title of the NFT', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='token_id',
            field=models.CharField(help_text='Unique identifier of the NFT', max_length=100, null=True, unique=True),
        ),
    ]
