# Generated by Django 5.0.1 on 2024-09-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_auction_nft_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='highest_bidder',
            new_name='owner',
        ),
    ]
