# Generated by Django 5.0.1 on 2024-09-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_highest_bidder_auction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='seller_wallet',
            field=models.CharField(help_text='Wallet Address', max_length=255, null=True),
        ),
    ]
